version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install --user websockets
          name: pip websockets
      - run:
          command: pip install --user JEWebSocket
          name: pip JEWebSocket
      - run:
          command: python Test/ServerUnitTest.py
          name: ServerUnitTest
      - run:
          command: python Test/ClientUnitTest.py
          name: ClientUnitTest


workflows:
  main:
    jobs:
      - build-and-test
