version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/save-cache
      - run:
          command: python JEWebSocket/Testpy/Websocket_Server_Test.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test